<?php

namespace app\api\controller;

use think\Controller;
use think\Request;

class Cross extends Controller
{
   protected function initialize()
   {
        parent::initialize(); // TODO: Change the autogenerated stub
        /*支持axios*/        
        header('Access-Control-Allow-Origin:*');
        header('Access-Control-Allow-Methods:GET,POST,PUT,DELETE,OPTIONS');
        header("Access-Control-Allow-Headers:Origin,X-Requested-With,Content-Type,Accept,x-accept-sign,x-accept-time,token");
        if(request() -> isOptions()){
            exit();
        }
   }
}
